include:
  - project: 'web/core/proton-config'
    ref: master
    file: '/_templates-ci/private-open.gitlab-ci.yaml'

variables:
    APP_GIT: "$APP_GIT_CI"
    NODE_OPTIONS: --max-old-space-size=4096
